Languagefiles/es-MX.xml

Spanish translation

---

Languagefiles/de-DE.xml

German Language

---

Languagefiles/ja-JP.xml

lang file of ja-JP.

---

Languagefiles/tr-TR.xml

"Save Config" and "Restore defaults" buttons may need their widths to be adjusted as their strings wrap.
_Ignore the en-US in the screenshot as it was done for testing purposes._

Add Turkish localization

---

Languagefiles/fr-FR.xml

It will allow French users to use correctly the app and with understanding.
And DWMBG is a great app. 🎉

Add French (France) language.

---

Languagefiles/fr-FR.xml

Changed un-translated text to French. Sorry!

Small update for FR-fr. 

---

README_FR.md

Allow French people to read the README.

Add a French README !

---

Languagefiles/pt-BR.xml

*I'm gonna rename my username to Nocthernet today, but later*

Add pt-BR translation

---

Languagefiles/it-IT.xml
README_IT.md

This commits adds The italian language to DWMBlurGlass. 
This has been tested to be working, Validated XML file, No errors found
Excuse me for my bad english im not very good at it sometimes.
At any case i might Update the Translation for any bad spelling or spelling mistakes.

Add Italian language 

---

README_IT.md

Updated Italian README to have the same look as the new English README

Refreshed Italian README

---

README_FR.md

It was outdated, so I translated the last english version.
And congrats for the 2.0 :)

Updated the French README in the last version.

---

DWMBlurGlassExt/DWMBlurGlassExt.vcxproj

Fixes building in machines with non-Unicode codepages.

Force UTF-8 encoding compilation

---

Languagefiles/en-US.xml
README.md

Improved English grammar in README and en-US.xml.

Improve English a bit more

---

Languagefiles/tr-TR.xml
README.md
README_DE.md
README_FR.md
README_IT.md
README_TR.md
README_ZH.md

This PR updates the Turkish language file based on the latest version of the English language file.

Extend and update Turkish translation

---

Languagefiles/tr-TR.xml

This PR adds Turkish translations for new strings added in 9b21c0e, and fixes some minor issues in the existing Turkish strings.

Update Turkish translation for v2.2.0 strings

---

Languagefiles/it-IT.xml

Added new Misc, Restore button translates

Updated Italian language file to 2.2.0

---

Languagefiles/de-DE.xml

Fatal error in xml Syntax wrong lang code | fixing Height to Size

Fatal error in xml Syntax wrong lang code | fixing Height to Size

---

Languagefiles/ja-JP.xml

Updated the Japanese translation file (ja-JP.xml) to include additional translations and fix some typos.

Update Japanese translation

---

Languagefiles/zh-TW.xml

update Traditional Chinese (v2.3.0)

---

Languagefiles/ru-RU.xml

new string for [2.3.1 release](https://github.com/Maplespe/DWMBlurGlass/releases/tag/2.3.1r)

loc: update Russian

---

Languagefiles/it-IT.xml

Updated italian that includes translation for the new Framerate Limit on the Release 2.3.1

2.3.1 Italian Update
